// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtuJ_nMf1j17OlAeI96OMf-Vwad8pYG2c',
    appId: '1:229279097522:web:178036e70d7d3fb0aadfab',
    messagingSenderId: '229279097522',
    projectId: 'binifiy',
    authDomain: 'binifiy.firebaseapp.com',
    databaseURL: 'https://binifiy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binifiy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlCYUyzo9ZnIrYaSD5g6QJBw3G4FKER-U',
    appId: '1:229279097522:android:5f3f267160c7fbb2aadfab',
    messagingSenderId: '229279097522',
    projectId: 'binifiy',
    databaseURL: 'https://binifiy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binifiy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunR88xWzyQldodw_0TApG1emhuqoZaDA',
    appId: '1:229279097522:ios:9681907110aeb03baadfab',
    messagingSenderId: '229279097522',
    projectId: 'binifiy',
    databaseURL: 'https://binifiy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binifiy.appspot.com',
    iosBundleId: 'com.example.binify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAunR88xWzyQldodw_0TApG1emhuqoZaDA',
    appId: '1:229279097522:ios:0f37af3fcaba89acaadfab',
    messagingSenderId: '229279097522',
    projectId: 'binifiy',
    databaseURL: 'https://binifiy-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binifiy.appspot.com',
    iosBundleId: 'com.example.binify.RunnerTests',
  );
}
